train_micro_batch_size_per_gpu: ${batch_size}
gradient_accumulation_steps: ${gradient_accumulation_steps}
num_gpus: ${devices}
bf16:
  enabled: ${is_bf16}
zero_optimization:
  stage: 1
  offload_optimizer:
    device: cpu
    pin_memory: true
    buffer_count: 4
    fast_init: false
  contiguous_gradients: true
gradient_clipping: ${max_grad_norm}
prescale_gradients: false
wall_clock_breakdown: false
memory_breakdown: true
checkpoint:
  tag_validation: ignore
  load_universal: true
  save_universal: true
save_16bit_model: true
save_full_weights: true