#!/bin/bash

num_machines=2
num_processes_per_machine=8
num_processes=$((num_machines * num_processes_per_machine))
machine_rank=0
main_process_ip="RANK0_NODE_IP"
main_process_port=29500
gpu_ids="0,1,2,3,4,5,6,7"

modality="text"
data_type="conversational"
split_ratio=1e-2
is_strict_split=False
dataset_name="tulu"
dataset_format="parquet"
is_preprocessed=False
strategy="deepspeed"
upload_user="Qwen"
model_type="Qwen3.5-9B"
revision="main"
left_padding=False
is_enable_thinking=False
is_quantized=False
is_peft=False
r=128
lora_alpha=512
target_modules="all-linear"
lora_dropout=0.0
max_length=4096
max_new_tokens=512
is_bf16=True
batch_size=4
eval_batch_size=4
gradient_accumulation_steps=4
teacher_model_type="Qwen3.6-27B"
loss_type=nll
lmbda=0.5
beta=0.5
seq_kd=False
use_uld_loss=False
num_generations=1
generation_batch_size=null
temperature=0.9
top_p=0.95
top_k=0
use_vllm=True
vllm_mode=colocate
vllm_tensor_parallel_size=1
gpu_memory_utilization=0.9
vllm_sync_frequency=1
lr=5e-6
weight_decay=1e-1
warmup_ratio=5e-2
epoch=2
step=250
workers_ratio=8
use_all_workers=False

accelerate launch \
    --num_machines=$num_machines \
    --num_processes=$num_processes \
    --machine_rank=$machine_rank \
    --main_process_ip=$main_process_ip \
    --main_process_port=$main_process_port \
    --same_network \
    --gpu_ids=$gpu_ids \
    main.py --config-name=gold.yaml mode=train \
    devices=$num_processes_per_machine \
    distributed.enabled=true \
    distributed.num_machines=$num_machines \
    distributed.num_processes_per_machine=$num_processes_per_machine \
    distributed.machine_rank=$machine_rank \
    distributed.main_process_ip=$main_process_ip \
    distributed.main_process_port=$main_process_port \
    distributed.validation_mode=error \
    modality=$modality \
    data_type=$data_type \
    split_ratio=$split_ratio \
    is_strict_split=$is_strict_split \
    dataset_name=$dataset_name \
    dataset_format=$dataset_format \
    is_preprocessed=$is_preprocessed \
    strategy=$strategy \
    upload_user=$upload_user \
    model_type=$model_type \
    revision=$revision \
    left_padding=$left_padding \
    is_enable_thinking=$is_enable_thinking \
    is_quantized=$is_quantized \
    is_peft=$is_peft \
    peft_config.r=$r \
    peft_config.lora_alpha=$lora_alpha \
    peft_config.target_modules=$target_modules \
    peft_config.lora_dropout=$lora_dropout \
    max_length=$max_length \
    max_new_tokens=$max_new_tokens \
    is_bf16=$is_bf16 \
    batch_size=$batch_size \
    eval_batch_size=$eval_batch_size \
    gradient_accumulation_steps=$gradient_accumulation_steps \
    teacher.model_type=$teacher_model_type \
    loss_type=$loss_type \
    lmbda=$lmbda \
    beta=$beta \
    seq_kd=$seq_kd \
    use_uld_loss=$use_uld_loss \
    num_generations=$num_generations \
    generation_batch_size=$generation_batch_size \
    generation_config.temperature=$temperature \
    generation_config.top_p=$top_p \
    generation_config.top_k=$top_k \
    use_vllm=$use_vllm \
    vllm_mode=$vllm_mode \
    vllm_tensor_parallel_size=$vllm_tensor_parallel_size \
    gpu_memory_utilization=$gpu_memory_utilization \
    vllm_sync_frequency=$vllm_sync_frequency \
    lr=$lr \
    weight_decay=$weight_decay \
    warmup_ratio=$warmup_ratio \
    epoch=$epoch \
    step=$step \
    workers_ratio=$workers_ratio \
    use_all_workers=$use_all_workers