#!/bin/bash

modality="text"
data_type="structural"
split_ratio=1e-2
is_strict_split=False
dataset_name="tulu"
dataset_format="parquet"
is_preprocessed=False
strategy="deepspeed"
upload_user="Qwen"
model_type="Qwen3.5-9B"
revision="main"
left_padding=False
is_enable_thinking=False
is_quantized=False
is_peft=False
r=128
lora_alpha=512
target_modules="all-linear"
lora_dropout=0.0
max_length=2048
max_new_tokens=512
is_bf16=True
batch_size=4
eval_batch_size=4
gradient_accumulation_steps=4
teacher_model_type="Qwen3.6-27B"
disable_dropout=False
ds3_gather_for_generation=True
shuffle_dataset=True
beta=1.0
temperature=0.7
top_p=0.8
top_k=20
min_p=null
repetition_penalty=1.0
use_vllm=True
vllm_mode="colocate"
vllm_tensor_parallel_size=1
gpu_memory_utilization=0.7
lr=5e-7
weight_decay=1e-1
warmup_steps=5e-2
epoch=2
step=250

accelerate launch main.py --config-name=distillation.yaml mode=train \
    modality=$modality \
    data_type=$data_type \
    split_ratio=$split_ratio \
    is_strict_split=$is_strict_split \
    dataset_name=$dataset_name \
    dataset_format=$dataset_format \
    is_preprocessed=$is_preprocessed \
    strategy=$strategy \
    upload_user=$upload_user \
    model_type=$model_type \
    revision=$revision \
    left_padding=$left_padding \
    is_enable_thinking=$is_enable_thinking \
    is_quantized=$is_quantized \
    is_peft=$is_peft \
    peft_config.r=$r \
    peft_config.lora_alpha=$lora_alpha \
    peft_config.target_modules=$target_modules \
    peft_config.lora_dropout=$lora_dropout \
    max_length=$max_length \
    max_new_tokens=$max_new_tokens \
    is_bf16=$is_bf16 \
    batch_size=$batch_size \
    eval_batch_size=$eval_batch_size \
    gradient_accumulation_steps=$gradient_accumulation_steps \
    teacher.model_type=$teacher_model_type \
    disable_dropout=$disable_dropout \
    ds3_gather_for_generation=$ds3_gather_for_generation \
    shuffle_dataset=$shuffle_dataset \
    beta=$beta \
    generation_config.temperature=$temperature \
    generation_config.top_p=$top_p \
    generation_config.top_k=$top_k \
    generation_config.min_p=$min_p \
    generation_config.repetition_penalty=$repetition_penalty \
    use_vllm=$use_vllm \
    vllm_mode=$vllm_mode \
    vllm_tensor_parallel_size=$vllm_tensor_parallel_size \
    gpu_memory_utilization=$gpu_memory_utilization \
    lr=$lr \
    weight_decay=$weight_decay \
    warmup_steps=$warmup_steps \
    epoch=$epoch \
    step=$step