structural:
  _target_: src.datasets.DPOStructuralDataset
  data_path: ${data_path}
  split_ratio: ${split_ratio}
  is_strict_split: ${is_strict_split}
  seed: ${seed}
  dataset_name: ${dataset_name}
  dataset_format: ${dataset_format}
  dataset_subdir: ${dataset_subdir}
  dataset_file_path: ${dataset_file_path}
  dataset_file_paths: ${dataset_file_paths}
  dataset_files: ${dataset_files}
  allow_dataset_file_name_mismatch: ${allow_dataset_file_name_mismatch}
  val_dataset_file_path: ${val_dataset_file_path}
  val_dataset_file_paths: ${val_dataset_file_paths}
  val_dataset_files: ${val_dataset_files}
  allow_val_dataset_file_name_mismatch: ${allow_val_dataset_file_name_mismatch}
  dataset_resampling: ${dataset_resampling}
  data_column_name: ${data_column_name}
  chosen_column_name: ${chosen_column_name}
  rejected_column_name: ${rejected_column_name}
  role_column_name: ${role_column_name}
  content_column_name: ${content_column_name}
  assistant_column_name: ${assistant_column_name}
  modality: ${modality}
  max_pixels: ${max_pixels}
  do_resize: ${do_resize}
  image_augmentation: ${image_augmentation}
  decode_image_paths: ${decode_image_paths}
  dataset_image: ${dataset_image}

conversational:
  _target_: src.datasets.DPOConversationalDataset
  data_path: ${data_path}
  split_ratio: ${split_ratio}
  is_strict_split: ${is_strict_split}
  seed: ${seed}
  dataset_name: ${dataset_name}
  dataset_format: ${dataset_format}
  dataset_subdir: ${dataset_subdir}
  dataset_file_path: ${dataset_file_path}
  dataset_file_paths: ${dataset_file_paths}
  dataset_files: ${dataset_files}
  allow_dataset_file_name_mismatch: ${allow_dataset_file_name_mismatch}
  val_dataset_file_path: ${val_dataset_file_path}
  val_dataset_file_paths: ${val_dataset_file_paths}
  val_dataset_files: ${val_dataset_files}
  allow_val_dataset_file_name_mismatch: ${allow_val_dataset_file_name_mismatch}
  dataset_resampling: ${dataset_resampling}
  prompt_column_name: ${prompt_column_name}
  chosen_column_name: ${chosen_column_name}
  rejected_column_name: ${rejected_column_name}
  modality: ${modality}
  max_pixels: ${max_pixels}
  do_resize: ${do_resize}
  image_augmentation: ${image_augmentation}
  decode_image_paths: ${decode_image_paths}
  dataset_image: ${dataset_image}