structural:
  _target_: src.datasets.GKDStructuralDataset
  data_path: ${data_path}
  split_ratio: ${split_ratio}
  is_strict_split: ${is_strict_split}
  seed: ${seed}
  dataset_name: ${dataset_name}
  dataset_format: ${dataset_format}
  dataset_subdir: ${dataset_subdir}
  dataset_file_path: ${dataset_file_path}
  allow_dataset_file_name_mismatch: ${allow_dataset_file_name_mismatch}
  data_column_name: ${data_column_name}
  target_column_name: ${target_column_name}
  role_column_name: ${role_column_name}
  content_column_name: ${content_column_name}
  assistant_column_name: ${assistant_column_name}

conversational:
  _target_: src.datasets.GKDConversationalDataset
  data_path: ${data_path}
  split_ratio: ${split_ratio}
  is_strict_split: ${is_strict_split}
  seed: ${seed}
  dataset_name: ${dataset_name}
  dataset_format: ${dataset_format}
  dataset_subdir: ${dataset_subdir}
  dataset_file_path: ${dataset_file_path}
  allow_dataset_file_name_mismatch: ${allow_dataset_file_name_mismatch}
  conversation_column_name: ${conversation_column_name}