structural:
  _target_: src.datasets.KTOStructuralDataset
  data_path: ${data_path}
  split_ratio: ${split_ratio}
  is_strict_split: ${is_strict_split}
  seed: ${seed}
  dataset_name: ${dataset_name}
  dataset_format: ${dataset_format}
  dataset_subdir: ${dataset_subdir}
  dataset_file_path: ${dataset_file_path}
  allow_dataset_file_name_mismatch: ${allow_dataset_file_name_mismatch}
  data_column_name: ${data_column_name}
  target_column_name: ${target_column_name}
  label_column_name: ${label_column_name}
  role_column_name: ${role_column_name}
  content_column_name: ${content_column_name}
  assistant_column_name: ${assistant_column_name}
  modality: ${modality}
  max_pixels: ${max_pixels}
  do_resize: ${do_resize}
  image_augmentation: ${image_augmentation}
  decode_image_paths: ${decode_image_paths}
  dataset_image: ${dataset_image}

conversational:
  _target_: src.datasets.KTOConversationalDataset
  data_path: ${data_path}
  split_ratio: ${split_ratio}
  is_strict_split: ${is_strict_split}
  seed: ${seed}
  dataset_name: ${dataset_name}
  dataset_format: ${dataset_format}
  dataset_subdir: ${dataset_subdir}
  dataset_file_path: ${dataset_file_path}
  allow_dataset_file_name_mismatch: ${allow_dataset_file_name_mismatch}
  prompt_column_name: ${prompt_column_name}
  completion_column_name: ${completion_column_name}
  label_column_name: ${label_column_name}
  modality: ${modality}
  max_pixels: ${max_pixels}
  do_resize: ${do_resize}
  image_augmentation: ${image_augmentation}
  decode_image_paths: ${decode_image_paths}
  dataset_image: ${dataset_image}