# @package _global_
defaults:
  - dataset: cpt_dataset
  - training_arguments: sft_config
  - trainer: sft_trainer
  - deepspeed: ds_config
  - hydra: hydra

package_name: llm-fine-tune-hf
project_dir: ${oc.env:PROJECT_DIR}/${package_name}
connected_dir: ${oc.env:CONNECTED_DIR}/${package_name}

seed: 2025

data_type: structural

split:
  train: train
  val: val

batch_size: 16
eval_batch_size: 16
workers_ratio: 8
use_all_workers: false

split_ratio: 1e-2
is_strict_split: true

dataset_name: tulu
dataset_format: parquet
is_sft: true
is_preprocessed: false
instruction_column_name: instruction
data_column_name: input
target_column_name: response
conversation_column_name: messages
role_column_name: role
content_column_name: content
assistant_column_name: assistant
upload_user: HuggingFaceTB
model_type: SmolLM2-135M-Instruct
pretrained_model_name: ${upload_user}/${model_type}
custom_data_encoder_path: ${connected_dir}/merged/data_encoders/${pretrained_model_name}
reference_data_encoder_name: HuggingFaceTB/SmolLM2-135M-Instruct
left_padding: false
merged_model_path: ${connected_dir}/merged/models/${pretrained_model_name}
max_length: 4096

user_name: ${oc.env:USER_NAME}
model_detail: ${model_type}
upload_tag: sft
model_path: ${user_name}/${model_detail}-${upload_tag}

is_quantized: false
quantization_config:
  load_in_4bit: true
  bnb_4bit_quant_type: nf4
  bnb_4bit_use_double_quant: true
  bnb_4bit_compute_dtype: bfloat16
is_peft: false
peft_config:
  r: 64
  lora_alpha: 16
  target_modules: all-linear
  lora_dropout: 0.1
  bias: none
  task_type: CAUSAL_LM
  inference_mode: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false

optim: paged_adamw_32bit
lr: 3e-5
weight_decay: 1e-1

scheduler_type: cosine
warmup_ratio: 5e-2

devices: ${oc.decode:${oc.env:DEVICES,null}}
strategy: deepspeed
logging_steps: 10
is_bf16: true
gradient_accumulation_steps: 8
max_grad_norm: 1
epoch: 5
step: 100

model_name: CausalLM-CPT
mode: train

project_name: ${model_name}-${dataset_name}-${mode}
total_batch_size: bs=${batch_size}x${devices}x${gradient_accumulation_steps}
length_info: max_length=${max_length}
save_detail: ${model_detail}-is_sft=${is_sft}-is_quantized=${is_quantized}-is_peft=${is_peft}-${length_info}-${total_batch_size}
logging_name: ${save_detail}-lr${lr}

output_dir: ${connected_dir}/checkpoints/${model_name}/${dataset_name}/${strategy}/${save_detail}
save_strategy: steps
save_total_limit: -1

resume_training: false
resume_from_checkpoint: null
use_validation: true
eval_strategy: epoch

dus_hidden_layers: 36
korean_model_name: beomi/OPEN-SOLAR-KO-10.7B
reasoning_model_name: Qwen/QwQ-32B
reasoning_tokens:
  - <think>
  - </think>

run_name: ${project_name}
work_dir: ${hydra:runtime.cwd}